#!/bin/bash
    clear
    echo -e "\033[46;1;37m            MANUTENÇÃO           \033[0m"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 💫 •\033[1;34m]\033[1;37m ➤  \033[1;33mPAINEL EM MANUTENÇÃO\033[0m"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[0;36m░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			3 | 01)
			mega
			;;
			3 | 02)
            mega
            ;;
			3 | 03)
            bash <(wget -qO- https://www.dropbox.com/s/wnwul8lj0p3s26u/sincpainel.sh?dl=0)
            ;;
			0 | 00)
			clear
			mega
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	fun_mega
}
